[functions]
  directory = "netlify/functions" # Or your functions directory

[[redirects]]
  from = "/api/netlify/directions" # Client will call this path
  to = "/.netlify/functions/extRoute"
  status = 200 