/*
 * Bazaar API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import ApproveUserDto from './model/ApproveUserDto';
import CreateUserDto from './model/CreateUserDto';
import LoginDTO from './model/LoginDTO';
import ProblemDetails from './model/ProblemDetails';
import UserInfoDto from './model/UserInfoDto';
import AdminApi from './api/AdminApi';
import FacebookAuthApi from './api/FacebookAuthApi';
import TestAuthApi from './api/TestAuthApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BazaarApi = require('index'); // See note below*.
* var xxxSvc = new BazaarApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BazaarApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BazaarApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BazaarApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApproveUserDto model constructor.
     * @property {module:model/ApproveUserDto}
     */
    ApproveUserDto,

    /**
     * The CreateUserDto model constructor.
     * @property {module:model/CreateUserDto}
     */
    CreateUserDto,

    /**
     * The LoginDTO model constructor.
     * @property {module:model/LoginDTO}
     */
    LoginDTO,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The UserInfoDto model constructor.
     * @property {module:model/UserInfoDto}
     */
    UserInfoDto,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The FacebookAuthApi service constructor.
    * @property {module:api/FacebookAuthApi}
    */
    FacebookAuthApi,

    /**
    * The TestAuthApi service constructor.
    * @property {module:api/TestAuthApi}
    */
    TestAuthApi
};
