/*
 * Bazaar API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LoginDTO model module.
 * @module model/LoginDTO
 * @version v1
 */
export default class LoginDTO {
  /**
   * Constructs a new <code>LoginDTO</code>.
   * @alias module:model/LoginDTO
   * @class
   * @param username {String} 
   * @param password {String} 
   */
  constructor(username, password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>LoginDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginDTO} obj Optional instance to populate.
   * @return {module:model/LoginDTO} The populated <code>LoginDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginDTO();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
LoginDTO.prototype.username = undefined;

/**
 * @member {String} password
 */
LoginDTO.prototype.password = undefined;

