/*
 * Bazaar API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserInfoDto model module.
 * @module model/UserInfoDto
 * @version v1
 */
export default class UserInfoDto {
  /**
   * Constructs a new <code>UserInfoDto</code>.
   * @alias module:model/UserInfoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInfoDto} obj Optional instance to populate.
   * @return {module:model/UserInfoDto} The populated <code>UserInfoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserInfoDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('emailConfirmed'))
        obj.emailConfirmed = ApiClient.convertToType(data['emailConfirmed'], 'Boolean');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], ['String']);
      if (data.hasOwnProperty('isApproved'))
        obj.isApproved = ApiClient.convertToType(data['isApproved'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserInfoDto.prototype.id = undefined;

/**
 * @member {String} userName
 */
UserInfoDto.prototype.userName = undefined;

/**
 * @member {String} email
 */
UserInfoDto.prototype.email = undefined;

/**
 * @member {Boolean} emailConfirmed
 */
UserInfoDto.prototype.emailConfirmed = undefined;

/**
 * @member {Array.<String>} roles
 */
UserInfoDto.prototype.roles = undefined;

/**
 * @member {Boolean} isApproved
 */
UserInfoDto.prototype.isApproved = undefined;

